### ISSUE TITLE
Electric Generators don't provide Electric Charge on load

### ISSUE THREAD

**Issue by JLLeitschuh** [FractalUK/KSPInterstellar#11]
See this post on your forum:
http://forum.kerbalspaceprogram.com/threads/43839-0-22-KSP-Interstellar-%28LFTR-Mining-MW-Thermal-Fusion%29-Version-0-8-2-%28Beta%29?p=817576&viewfull=1#post817576

Great job!

**Comment by FractalUK** [comment]
Fixed in 0.8.2
