### ISSUE TITLE
Dissipation bugs

### ISSUE THREAD

**Issue by anirul** [FractalUK/KSPInterstellar#13]
I'm using a space plane with a antimatter tank and 4 radial radiators and if the warp speed is > 100 the waste heat is no more dissipated (and the ship explode). I don't know if it is related but I m using the planet factory addon that probably messes up the time warp.'

I could provide the craft file if needed.

**Comment by FractalUK** [comment]
Thermals mechanics have been vastly altered in the latest version and old problems should be resolved, if you have further trouble in the future, create a new issue.
