### ISSUE TITLE
Move definitions of atmospheres to cfg

### ISSUE THREAD

**Issue by seanth** [FractalUK/KSPInterstellar#14]
It'd be nice if there were a user-configurable cfg file that defined the atmospheric content of each planet/moon. 

It'd be even nicer if the dll and the definitions were their own mod so one could define atmosphere compositions without requiring the rest of KSPI. Not that KSPI isn't great, mind.

**Comment by FractalUK** [comment]
This is in my list of plans for future versions and will make it into the mod at some point in the not-too-distant future.  I don't plan to seperate anything out of KSPI, but similar to the planetary resource definitions, it will be possible for other mods to define their own atmospheric resources.

**Comment by FractalUK** [comment]
This is now included in the mod
