### ISSUE TITLE
Fusion reactors give incorrect message when given insufficient electricity

### ISSUE THREAD

**Issue by willglynn** [FractalUK/KSPInterstellar#19]
[FNFusionReactor.getResourceDeprivedMessage()](https://github.com/FractalUK/KSPInterstellar/blob/master/FNPlugin/FNFusionReactor.cs#L128) always returns `fuelmodeStr + " deprived"`, even when the reactor is [shut down due to insufficient electricity](https://github.com/FractalUK/KSPInterstellar/blob/master/FNPlugin/FNFusionReactor.cs#L107-L110).

Steps to reproduce:
1. Assemble a vehicle containing a probe body with a 1.25m fusion reactor and 1.25m thermal turbojet below, a ram-air intake above, and an RTG.
2. Proceed to launch pad.
3. Throttle up and press spacebar to stage.
4. Inspect the reactor.

Expected results: reactor shows "Status: MegaJoules deprived!"
Actual results: reactor shows "Status: Deuterium/Tritium deprived!"

**Comment by FractalUK** [comment]
This is a known issue and will be fixed in the next update.
