### ISSUE TITLE
Wrong Information for Thermal Rockets in VAB

### ISSUE THREAD

**Issue by KarlSpaat** [FractalUK/KSPInterstellar#21]
The information in the VAB about the Thermal Rockets are incorrect. Every diameter of Thermal Rocket has listed a maximum thrust of 500.

**Comment by FractalUK** [comment]
The ModuleEngines information used to be hidden before the release of 0.23 but the method for hiding that information has apparently changed, it may or may not be possible to hide this information again.  Until then, ignore the information in the engine module and look at the FNNozzle Controller information.

**Comment by FractalUK** [comment]
This information was once again hidden.
