### ISSUE TITLE
Solar panels + electric generator should work

### ISSUE THREAD

**Issue by krillr** [FractalUK/KSPInterstellar#25]
It makes little sense that you can transmit copious quantities of power via solar + microwave, but can't use some of that power locally to power things like plasma thrusters,   antimatter containment, etc. Making this work opens the door to some very neat Low Kerbol Orbit satellite and space station possibilities!

**Comment by FractalUK** [comment]
Please keep this section for issues, not feature requests.  New features can be discussed on the forum thread.
