### ISSUE TITLE
Solar power generation tops out at 61.750 MW

### ISSUE THREAD

**Issue by fernandodlc** [FractalUK/KSPInterstellar#39]
Longstanding issue with Microwave beamed power.

At some point you reach a hard limit for power generation, no matter how many panels or how close to Kerbol you get you cannot transmit more than 61.750 MW of beamed power from a solar station.

Probably known, just logging it

**Comment by ArtForz** [comment]
Let me check my crystal ball....your transmitter vessel has storage for about 1235 ElectricCharge.
Try adding more batteries.
With KSPi 0.11, you need about sum(solar panel Energy Flow) \* FixedDeltaTime worth of EC storage on the transmitter vessel.
For gigantors in low Kerbol orbit, that comes out to a bit under 1000 EC per panel.

**Comment by fernandodlc** [comment]
Awesome, I knew there must be a reason, I could not for the life of me find any info on it.

Will edit bug to make this a documentation bug/feature rather than a software one then.

I should be able to contribute to the wiki. Now I know what I am looking for I should be able to figure it out and update it which I will do hopefully this weekend.

Thanks
