### ISSUE TITLE
[solved] Can't log magnetometer data

### ISSUE THREAD

**Issue by shrx** [FractalUK/KSPInterstellar#46]
_UPDATE_
The title was wrong, I wanted to say that I can't _Log_ Magnetopsheric Data, not _collect_ it.

I have put a Dual Technique Magnetometer on my satellite. I can only 
[activate](https://cloud.githubusercontent.com/assets/810337/3375846/c7f87934-fbce-11e3-8034-e0f422dd7126.png) or [deactivate](https://cloud.githubusercontent.com/assets/810337/3375852/d21730a4-fbce-11e3-83cb-5d74ef8898c4.png) the sensor, I can't ~~collect~~ log the science data. I've looked in my persistent.sfs and it looks like this:

```
                MODULE
                {
                    name = ModuleScienceExperiment
                    isEnabled = True
                    Deployed = False
                    Inoperable = False
                    EVENTS
                    {
                        DeployExperiment
                        {
                            active = False
                            guiActive = True
                            guiIcon = Deploy
                            guiName = Log Magnetopsheric Data
                            category = Deploy
                            guiActiveUnfocused = False
                            unfocusedRange = 2
                            externalToEVAOnly = True
                        }
```

I changed the `active = False` in `DeployExperiment` to `active = True` in my quicksave.sfs and reloaded the saved game but it had no effect. Any suggestions?

**Comment by confusingbits** [comment]
The problem lies in the part config. Here's is a corrected version.

https://github.com/WaveFunctionP/KSPInterstellar/blob/master/GameData/WarpPlugin/Parts/Utility/DTMagnetometer/part.cfg

In particular

dataIsCollectable = True
collectActionName = Take Data
interactionRange = 1.2

I'm not sure exactly how to edit the save file to correct the issue directly.

**Comment by shrx** [comment]
Sorry for the confusion. I actually meant that I can't _Log_ Magnetopsheric Data, not _collect_ it. As in, there is no **Log Magnetopsheric Data** button in the magnetometer's menu. I will edit the question.

**Comment by confusingbits** [comment]
Are you sure that you are a place where you log data and that your vessel is still powered and you have command? Do any context menu buttons show up, cause that is a ksp bug as well.

**Comment by shrx** [comment]
The screenshots I linked to in the question ([1](https://cloud.githubusercontent.com/assets/810337/3375846/c7f87934-fbce-11e3-8034-e0f422dd7126.png), [2](https://cloud.githubusercontent.com/assets/810337/3375852/d21730a4-fbce-11e3-83cb-5d74ef8898c4.png)) are taken from a 700 km high circular orbit around Kerbin. Should the sensor work here? This is the first time I tried to use this sensor, I've only just started with the Interstellar mod.

**Comment by shrx** [comment]
Small follow up:
I started a completely new game with only KSP Interstellar mod v0.11 installed.
I edited the save file to get some science to research the magnetometer sensor and launched two spacecrafts with it, one in ~70 km and one in ~900 km orbit around kerbin. I still can't log magnetospheric data from any of them. Here is the save file if it's of any help: https://www.dropbox.com/s/igp6136pwtfrnhj/megnetotest.zip

**Comment by confusingbits** [comment]
Strange. It should say "Log Magnetospheric Data" on the button. I would suggest  deleting the old warpplugin folder, downloading the mod, and placing it in gamedata again.

**Comment by shrx** [comment]
No luck, this new game is with a freshly downloaded mod from the official forum page.
I've also tried assigining data logging to an action group but it still doesn't work.

**Comment by confusingbits** [comment]
I've seen corrupted installs before. You may need to reinstall if you don't have clean install to copy.

To be clear you don't have any plugins in game directory other than the gamedata folder do you? Third party plugins should go into the gamedata folder, not the plugins/parts/ships folders.

**Comment by shrx** [comment]
OK, will try this.

**Comment by shrx** [comment]
You were right, it looks my game files got corrupted somehow. Redownloaded the game from steam and now it works.

**Comment by confusingbits** [comment]
Awesome! Have fun. :)
