### ISSUE TITLE
Antimatter Reactors and Science Lab Glitch

### ISSUE THREAD

**Issue by xATHEISTxDEITYx** [FractalUK/KSPInterstellar#52]
At launch of any craft containing a Science Lab or an Antimatter Reactor, Surface Velocity will read 174.6 m/s before liftoff. After liftoff, no vertical speed is measured, but craft will fly into space regardless of engine setup. Attitude is difficult to control, and even cheating into orbit causes strange happenings. Using Mechjeb embedded and NearFuture mods in conjunction.

**Comment by confusingbits** [comment]
The official version here does not support the current version of ksp.

**Comment by xATHEISTxDEITYx** [comment]
Any plans on upgrading this mod? If not, is there a work-around?

**Comment by confusingbits** [comment]
I have a working version. You can watch the interstellar thread for updates.

https://github.com/WaveFunctionP/KSPInterstellar/releases

Be sure to delete all the old files from the official version, including treeloader and ORS.

**Comment by xATHEISTxDEITYx** [comment]
Thanks, I'll give the experimental a shot and see how the parts react. Looking forward to really playing this mod!
