### ISSUE TITLE
Most fission reactors have same 'akula' description

### ISSUE THREAD

**Issue by FalcoGer** [FractalUK/KSPInterstellar#78]
The fission reactors except for open/closed cycle and the molten salt one have the same description of the akula reactor. The akula reactor itself is nowhere to be found.

**Comment by sswelm** [comment]
yes, they should indeed get a better description. Perhaps you can help me by creating good descriptions

**Comment by FalcoGer** [comment]
I'm just gonna close this. It's too old to bother anymore.
