### ISSUE TITLE
Reactors upgrades show in VAB/SPH as seperate parts

### ISSUE THREAD

**Issue by FalcoGer** [FractalUK/KSPInterstellar#79]
I'm pretty sure it should just upgrade the existing parts. Also most descriptions don't include the upgrade information.
The supposedly upgraded reactors have the same stats in the description

**Comment by sswelm** [comment]
Yes, they are mend as place holder to show th players the technodes unlock higher tech of a particular  reactor.. I should only consistently name them Upgrade

**Comment by FalcoGer** [comment]
I'm just gonna close this. It's too old to bother anymore.
