### ISSUE TITLE
MM error

### ISSUE THREAD

**Issue by 7ranceaddic7** [FractalUK/KSPInterstellar#87]
Getting this in the KSP.log.

1 error related to GameData/WarpPlugin/Patches/RealFuelsFix.cfg

I found this on ln20:

@TANK_DEFINITION[ServiceModule,Fuselage,Jet,Xenon]:NEEDS[RealFuels]:FOR[WarpPlugin]:Final

FIX:

remove :Final

**Comment by sswelm** [comment]
fixed, but please report any KSPIE bugs at https://github.com/sswelm/KSP-Interstellar-Extended/issues

**Comment by 7ranceaddic7** [comment]
Noted for future use; thanks.
