### ISSUE TITLE
Retrofitting computer core crashes on linux

### ISSUE THREAD

**Issue by ArtForz** [FractalUK/KSPInterstellar#9]
Suspect 
https://github.com/FractalUK/KSPInterstellar/blob/master/FNPlugin/ComputerCore.cs#L169
should be "GameData/WarpPlugin/NameList.cfg" (case sensitive)

**Comment by dhxgit** [comment]
I made a pull-request with the required fix, in #10

**Comment by FractalUK** [comment]
0.8 update will fix this issue.
