### ISSUE TITLE
Oversized Microwave Dish Transiever don't show activate transmitter option

### ISSUE THREAD

**Issue by thiagohmoreira** [FractalUK/KSPInterstellar#92]
Hello,

I've struggle for far to much time trying to figure this out. And I may be just doing something terrible wrong, but so far I believe there is some sort of bug messing with me.

Bellow is a simple test rig I've put together (reactor -> thermal gen -> batteries -> gyrotron -> dish). I cannot get the dish to allow me to enable transmitter. From dish description I think this should work, but I could not find any examples using these items, nor wiki page... so, once more I might be just me...

![image](https://user-images.githubusercontent.com/2332721/63171627-39b14380-c03c-11e9-8dd7-8eeb585bb4cc.png)

Any ideas?

**Comment by sswelm** [comment]
It cannot function on the Surface. Try again in space. The reason is that it needs to be able to turn, which can only be done in space as it is pivotless. Dishes need to be pointed directly to their target. If you want to use microwave beamed power on the surface, use a deployable phased array

**Comment by thiagohmoreira** [comment]
@sswelm Hey mate, thanks! I've closed the issue here cause I've figured this was the wrong place to ask this question (I was browsing sources to see if I could figure something ^^, and ended up with many open tabs... and well =D). In fact I've raised this on your repo. I'll test this out and add this info there and also close it. Again, thanks a lot for the answer!
